import AppFooter from '@/components/AppFooter';
import FixedBar from '@/components/FixedBar';
import Header from '@/components/Header.jsx'
import { Inter } from 'next/font/google';
import './globals.sass'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <main>
        <Header/>
        {children}
        <AppFooter/>
        <FixedBar/>
        </main>
      </body>
    </html>
  )
}
